version: '3.8'

services:
  kong-service:
    build: .
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/kong/config.yml
      - KONG_PLUGINS=bundled,header-validation
      - KONG_PLUGINSERVER_NAMES=header-validation
      - KONG_PLUGINSERVER_HEADER_VALIDATION_START_CMD=/kong/go-plugins/header-validation
      - KONG_PLUGINSERVER_HEADER_VALIDATION_QUERY_CMD=/kong/go-plugins/header-validation -dump
    volumes:
      - ./config.yml:/kong/config.yml
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8443:8443'
      - '8444:8444'